version: 2.1

description: Tasks for managing Rails assets in CircleCI builds

display:
  home_url: "https://github.com/boxt/orbs"
  source_url: "https://github.com/boxt/rails-assets-orb/blob/master/config.yml"

commands:
  precompile:
    steps:
      - run:
          name: "Precompile assets"
          command: bundle exec rails assets:precompile

  cache-read:
    steps:
      - restore_cache:
          keys:
            - assets-cache-{{ .Environment.CIRCLE_SHA1 }}
  cache-write:
    steps:
      - save_cache:
          key: assets-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./public/assets
            - ./public/packs-test
