version: 2.1

description: Tasks for managing Rails assets in CircleCI builds

display:
  home_url: "https://github.com/boxt/orbs"
  source_url: "https://github.com/boxt/rails-assets-orb/blob/main/config.yml"

commands:
  assets-cache-key:
    steps:
      - run:
          name: Generate assets cache key
          command: find app/javascript -type f -exec md5sum {} \; > assets_cache_key
  cache-read:
    steps:
      - assets-cache-key
      - restore_cache:
          keys:
            - assets-cache-{{ arch }}-{{ .Branch }}-{{ checksum "assets_cache_key" }}
  cache-write:
    steps:
      - assets-cache-key
      - save_cache:
          key: assets-cache-{{ arch }}-{{ .Branch }}-{{ checksum "assets_cache_key" }}
          paths:
            - public/assets
            - public/packs-test
            - tmp/cache/assets
            - tmp/cache/webpacker
  precompile:
    steps:
      - run:
          name: "Precompile assets"
          command: bundle exec rails assets:precompile
